version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    container_name: selenium_hub
    ports: 
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '512m'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: rijuvijayan/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result:/usr/share/selenium-docker/test-output
  book-flight-module:
    image: rijuvijayan/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - ./booking-results:/usr/share/selenium-docker/test-output